### PR TITLE
Remove ipdb dependency

### PR DESCRIPTION
**Pull request by fmrsabino**
- Removes `ipdb` from the project as this dependency is not being used.

### CODE REVIEW

**Comment by Uxio0** [comment]
This is a dev requirement not affecting production image. Maybe you are not using it, but `ipdb` is required for debugging. I don't think it should be removed

**Comment by fmrsabino** [comment]
I also have no strong opinion regarding this but I see the `dev` requirements as the dependencies that we use to validate the state of the project but that should not be bundled. So for each dependency it'd be good to understand why we have it listed.

**Comment by Uxio0** [comment]
IMHO dev dependencies are meant for development, and they are a sane standard for working in the project, without requiring the user to go search for the needed tools. Ipdb is a really basic dev dependency, and I wouldn't remove it

**Comment by fmrsabino** [comment]
> IMHO dev dependencies are meant for development, and they are a sane standard for working in the project, without requiring the user to go search for the needed tools. Ipdb is a really basic dev dependency, and I wouldn't remove it

Ok I will close the PR 👍 (as mentioned I don't have a strong opinion on this matter but a slight preference to reduce the number of dependencies that the project lists and leave the dev environment open for each user when it comes to tooling).

**Pull request closed without merging**
